# Generated by Django 4.2.4 on 2023-08-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('certificate_id', models.CharField(max_length=10, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('admission_year', models.PositiveIntegerField()),
                ('graduation_year', models.PositiveIntegerField()),
                ('access_code', models.CharField(max_length=10, unique=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
    ]
