# Generated by Django 4.2.4 on 2023-09-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_certificate_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='certificate_image',
            field=models.ImageField(default='media/certicates/image.jpg', upload_to='certificates/'),
        ),
    ]
